image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - publish

before_script:
  - echo "Setting up environment"
  - 'dotnet --version'

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore
  artifacts:
    paths:
      - "**/bin/Release"

test:
  stage: test
  script:
    - dotnet test --no-restore --verbosity normal

publish:
  stage: publish
  script:
    - dotnet pack -c Release -o .
    - for nupkg in *.nupkg; do dotnet nuget push $nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json; done
  only:
    - main
  variables: 
    NUGET_API_KEY: $NUGET_API_KEY
