<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Faker.Net" Version="2.0.163" />
        <PackageReference Include="Microsoft.AspNetCore.App.Internal.Assets" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\HopFrame.Web\HopFrame.Web.csproj" />
    </ItemGroup>

</Project>
