<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        
        <IsPackable>true</IsPackable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>HopFrame.Web</PackageId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="../../README.md">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.0"/>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.2" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.11.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HopFrame.Core\HopFrame.Core.csproj" />
    </ItemGroup>

</Project>
