<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>HopFrame.Web</PackageId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.5" />
        <PackageReference Include="MudBlazor" Version="9.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HopFrame.Core\HopFrame.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>HopFrame.Tests.Web</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
