<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\HopFrame.Core\HopFrame.Core.csproj" />
      <ProjectReference Include="..\..\src\HopFrame.Web\HopFrame.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Faker.Net" Version="2.0.163" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
    </ItemGroup>

</Project>
