<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>HopFrame.Core</PackageId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <Description>HopFrame is a lightweight extension library for existing .NET applications that adds administrative Blazor pages on top of your current data model. It connects to your configured databases and provides ready‑to‑use CRUD views so you can browse, filter, create, update, and delete data without writing custom admin UIs.</Description>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://git.leon-hoppe.de/leon.hoppe/HopFrame</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>HopFrame.Tests.Core</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
