<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <IsPackable>true</IsPackable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>HopFrame.Core</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="../../README.md">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>HopFrame.Tests.Core</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
